version: "3.8"

services:
  backend:
    container_name: hotel-backend
    build:
      context: ./server
    ports:
      - "5000:5000"
    networks:
      - hotel-network

  frontend:
    container_name: hotel-frontend
    build:
      context: ./client
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - hotel-network

networks:
  hotel-network:
    driver: bridge