services:
  frontend:
    container_name: hotel-frontend
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - hotel-network

  backend:
    container_name: hotel-backend
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - hotel-network

networks:
  hotel-network:
    driver: bridge